- name: ServiceNow CI/CD Rollback Plugin
  # You may pin to the exact commit or the version.
  # uses: ServiceNow/sncicd-plugin-rollback@600e3f11252fa6690ea329d129854eed2ed3f291
  uses: ServiceNow/sncicd-plugin-rollback@2.0.0
  with:
    # Plugin ID to be rolled back
    pluginID: 
